###############################################################################
# Benchmarking Configuration (2026)
#
# Author: Vittoria De Pellegrini
# Affiliation: PhD Student, King Abdullah University of Science and Technology
#
# Description: Fourier_MIONet/train_dp.yaml
#              Configuration file for benchmarking model training, evaluation,
#              timing, and result aggregation workflows.
###############################################################################

# Fourier-MIONet pressure buildup training config
seed: 0
n_frames: 17
ntrain: 4500
ntest: 500

# Folder containing dP_data/training_dataset_pressure_buildup and dP_data/validation_dataset_pressure_buildup
# Update this path for your environment

data_dir: /.../LAViG-FLOW/pressure_buildup_vae
save_dir: saved_models

optimizer: rmsprop
learning_rate: 1.0e-3
decay_step: 3375
decay_gamma: 0.9
loss_weights: [1.0, 0.5]

# n_epochs = 150 
iterations: 168750
batch_size: 4 
timestep_batch_size: 8 
training_time_size: 17

display_every: 500
save_every: 3375
save_better_only: true

# Model sizes
modes1: 10
modes2: 10
width: 36
width2: 128

# Evaluation
# Number of samples to evaluate (use <= ntest)
eval_samples: 10

wandb:
  group: fourier_mionet
  enable: true
  project: benchmarking
  # entity:
  # name:
  # tags: []
  # group:
